


package MyVisualization;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import javax.swing.*;
import MyVisualization.MyMainFrame;
/**
 *
 * @author ZhangYuyan,2019308160102,20210813
 */
public class MyLogin extends javax.swing.JFrame {

    /**
     * Creates new form MyLogin
     */
    public MyLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        backgoundPanel = new javax.swing.JPanel();
        titlelabel = new javax.swing.JLabel();
        jBtLogin = new javax.swing.JButton();
        jBtOpenReadme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("登录MyAccessViewer");
        setBackground(new java.awt.Color(0, 153, 255));

        backgoundPanel.setBackground(new java.awt.Color(250, 250, 250));

        titlelabel.setBackground(new java.awt.Color(204, 204, 255));
        titlelabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        titlelabel.setText("   Log in MyAccessViewer");
        titlelabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jBtLogin.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        jBtLogin.setText("登录");
        jBtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLoginActionPerformed(evt);
            }
        });

        jBtOpenReadme.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        jBtOpenReadme.setText("查看说明文档");
        jBtOpenReadme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtOpenReadmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgoundPanelLayout = new javax.swing.GroupLayout(backgoundPanel);
        backgoundPanel.setLayout(backgoundPanelLayout);
        backgoundPanelLayout.setHorizontalGroup(
            backgoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgoundPanelLayout.createSequentialGroup()
                .addGroup(backgoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgoundPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jBtLogin)
                        .addGap(107, 107, 107)
                        .addComponent(jBtOpenReadme))
                    .addGroup(backgoundPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        backgoundPanelLayout.setVerticalGroup(
            backgoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgoundPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(backgoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtLogin)
                    .addComponent(jBtOpenReadme))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgoundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgoundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void jBtLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyMainFrame().setVisible(true);
                dispose();
            }
        });
    }                                        

    private void jBtOpenReadmeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        try {
            String readFilePath = System.getProperty("user.dir")
            + "\\readme.md";
            File f = new File(readFilePath);
            if (f.exists()) {
		Runtime.getRuntime().exec("notepad " + readFilePath);
                            }
	} catch (IOException e1) {
		e1.printStackTrace();
		}
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyLogin().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel backgoundPanel;
    private javax.swing.JButton jBtLogin;
    private javax.swing.JButton jBtOpenReadme;
    private javax.swing.JLabel titlelabel;
    // End of variables declaration                   
}